#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
  x86_64)
    SYSTEM_TYPE="x86_64-linux"
    ;;
  aarch64)
    SYSTEM_TYPE="aarch64-linux"
    ;;
  *)
    echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
    exit 1
    ;;
esac

echo -e "${YELLOW}Checking if home-manager is installed...${NC}"
if ! command -v home-manager >/dev/null 2>&1; then
  echo -e "${YELLOW}home-manager not found. Using nix to run it temporarily...${NC}"
  nix shell --extra-experimental-features 'nix-command flakes' nixpkgs#home-manager -c home-manager switch --flake .#${SYSTEM_TYPE} "$@"
fi

echo "${GREEN}Switch to new generation complete!${NC}"
