[project]
name = "docs"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "sphinx",
    "myst-parser",
    "sphinx-copybutton",
    "furo",
    "doc8",
    "rstcheck",
    "esbonio",
]
