# source: https://github.com/sphinx-notes/pages
name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
    - uses: actions/checkout@master
    - name: Install python depedencies
      run: |
        cd docs
        pip install .
        cd ..
        
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: docs/source/
        requirements_path: ""
        pyproject_extras: ""
        checkout: false
        